name: Build node js
on: push
jobs:
  build-node:
   runs-on: ubuntu-latest
   container: node:18
   steps:
     - run: node --version
     - run: npm --version
     - uses: actions/checkout@v3
     - name: install apt
       run: apt-get update && apt-get install -y && apt install ffmpeg -y && apt install imagemagick -y
     - name: install module
       run: npm install
     - name: unzip
       run: unzip session.zip
     - name: start
       run: node juna.js
   
